[package]
name = "stratum-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
netstat2 = "0.11"
sysinfo = "0.30.5"
bollard = "0.15"
tokio = { version = "1.36", features = ["full"] }
futures = "0.3"
